services:
  app:
    container_name: server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./sqlite_dbs:/app/sqlite_dbs