[client]
showSidebarNavigation = false

[server]
headless = true
runOnSave = true
address = "0.0.0.0"

[theme]
base = "dark"
primaryColor = "transparent"
backgroundColor = "#090a0f"
textColor = "#7289da"
font = "sans serif"